import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaSparkContext;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mgruc' at '11/22/16 5:57 PM' with Gradle 2.5
 *
 * @author mgruc, @date 11/22/16 5:57 PM
 */
public class SparkKMeansExampleApplication {


    /**
     * If you want to run a spark cluster locally:
     * 1. Download it from http://spark.apache.org/downloads.html
     * 2. unzip it
     * 3. start it by ./sbin/start-master.sh
     *
     *
     * @param args
     */
    public static void main (String args[])  {

        SparkConf conf = new SparkConf().setAppName("SparkKMeansExampleApplication").setMaster("local");
        JavaSparkContext sc = new JavaSparkContext(conf);

        try {
            Thread.sleep(100000);

        } catch (Exception e) {

        }
    }
}
