import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mgruc' at '11/22/16 5:57 PM' with Gradle 2.5
 *
 * @author mgruc, @date 11/22/16 5:57 PM
 */
public class SparkKMeansExampleApplicationTest {

    /*
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    */
}
